insert into club (club_name, club_manager, club_ground) values
("Arsenal", "Arsene Wenger", "Emirates"),
("Aston Villa", "",),
("Brnley",),
("Chelsea"),
("Crystal Palace"),
("Everton"),
("Hull City"),
("Leicester"),
("Liverpool"),
("Manchester City"),
("Manchester United"),
("Newcastle United"),
("Queens Park Rangers"),
("Southampton"),
("Stoke City"),
("Sunderland"),
("Swansea City"),
("Tottenham Hotspur"),
("West Bromwich Albion"),
("West Ham");