insert into club (club_name, club_manager, club_ground) values
("Arsenal", "Arsene Wenger", "Emirates"),
("Aston Villa", "Paul Lambert", "Villa Park"),
("Burnley", "Sean Dyche", "Turf Moor"),
("Chelsea", "Jose Mourinho", "Stamford Bridge"),
("Crystal Palace", "Neil Warnock", "Selhurst Park"),
("Everton", "Roberto Martinez", "Goodison Park"),
("Hull City", "Steve Bruce", "KC Stadium"),
("Leicester City", "Nigel Pearson", "King Power Stadium"),
("Liverpool", "Brendan Rogers", "Anfield"),
("Manchester City", "Manuel Pellegrini", "City of Manchester Stadium"),
("Manchester United", "Louis van Gaal", "Old Trafford"),
("Newcastle United", "Alan Pardew", "St James' Park"),
("Queens Park Rangers", "Harry Redknapp", "Loftus Road"),
("Southampton", "Ronald Koeman", "St Mary's Stadium"),
("Stoke City", "Mark Hughes", "Britannia Stadium"),
("Sunderland", "Gus Poyet", "Stadium of Light"),
("Swansea City", "Gary Monk", "Liberty Stadium"),
("Tottenham Hotspur", "Mauricio Pochettino", "White Hart Lane"),
("West Bromwich Albion", "Alan Irvine", "The Hawthorns"),
("West Ham", "Sam Allardyce", "Upton Park");