insert into club (club_name, club_manager, club_ground) values
("Arsenal", "Arsene Wenger", "Emirates"),
("Aston Villa", "",),
("Barnley",),
("Chelsea", "Jose Mourihno", "Stamford Bridge"),
("Crystal Palace"),
("Everton"),
("Hull City"),
("Leicester"),
("Liverpool", "Anfield"),
("Manchester City", "Etihad"),
("Manchester United", "Old Trafford"),
("Newcastle United", "Sports Direct Stadium"),
("Queens Park Rangers"),
("Southampton"),
("Stoke City"),
("Sunderland"),
("Swansea City"),
("Tottenham Hotspur"),
("West Bromwich Albion"),
("West Ham");