insert into homeTeam (fixture_id, club_name, goals, venue) values
("f001", "Manchester United", "1", "Old Trafford"),
("f002", "Leicester City", "2", "King Power Stadium"),
("f003", "Queens Park Rangers", "0", "Loftus Road"),
("f004", "Stoke City", "0",  "Britannia Stadium"),
("f005", "West Bromwich Albion", "2",  "The Hawthorns"),
("f006", "West Ham", "0", "Upton Park"),
("f007", "Arsenal", "2", "Emirates"),
("f008", "Liverpool", "2", "Anfield"),
("f009", "Newcastle United", "0", "St James' Park"),
("f010", "Burnley", "1", "Turf Moor"),
("f011", "Aston Villa", "0", "Villa Park"),
("f012", "Chelsea", "2", "Stamford Bridge"),
("f013", "Crystal Palace", "1", "Selhurst Park"),
("f014", "Southampton", "0", "St Mary's Stadium"),
("f015", "Swansea City", "1", "Liberty Stadium"),
("f016", "Everton", "2", "Goodison Park"),
("f017", "Hull City", "1", "KC Stadium"),
("f018", "Tottenham Hotspur", "4", "White Hart Lane"),
("f019", "Sunderland", "1", "Stadium of Light"),
("f020", "Manchester City", "3", "City of Manchester Stadium"),
("f021", "Burnley", "0", "Turf Moor"),
("f022", "Manchester City", "0", "City of Manchester Stadium"),
("f023", "Newcastle United", "3", "St James' Park"),
("f024", "Queens Park Rangers", "1", "Loftus Road"),
("f025", "Swansea City", "3", "Liberty Stadium"),
("f026", "West Ham", "1", "Upton Park"),
("f027", "Everton", "3", "Goodison Park"),
("f028", "Aston Villa", "2", "Villa Park"),
("f029", "Tottenham Hotspur", "0", "White Hart Lane"),
("f030", "Leicester City", "1",  "King Power Stadium"),
("f031", "Arsenal", "2",  "Emirates"),
("f032", "Chelsea", "4", "Stamford Bridge"),
("f033", "Crystal Palace", "0", "Selhurst Park"),
("f034", "Southampton", "4", "St Mary's Stadium"),
("f035", "Stoke City", "0", "Britannia Stadium"),
("f036", "Sunderland", "2", "Stadium of Light"),
("f037", "West Bromwich Albion", "0", "The Hawthorns"),
("f038", "Liverpool", "0", "Anfield"),
("f039", "Manchester United", "4",  "Old Trafford"),
("f040", "Hull City", "2", "KC Stadium"),
("f041", "Queens Park Rangers", "2", "Loftus Road"),
("f042", "Aston Villa", "0", "Villa Park"),
("f043", "Burnley", "0", "Turf Moor"),
("f044", "Newcastle United", "2", "St James' Park"),
("f045", "Swansea City", "0", "Liberty Stadium"),
("f046", "West Ham", "3", "Upton Park"),
("f047", "Leicester City", "5", "King Power Stadium"),
("f048", "Tottenham Hotspur", "0",  "White Hart Lane"),
("f049", "Everton", "2", "Goodison Park"),
("f050", "Manchester City", "1", "City of Manchester Stadium"),
("f051", "Liverpool", "1", "Anfield"),
("f052", "Chelsea", "3", "Stamford Bridge"),
("f053", "Crystal Palace", "2", "Selhurst Park"),
("f054", "Hull City", "2", "KC Stadium"),
("f055", "Manchester United", "2",  "Old Trafford"),
("f056", "Southampton", "2", "St Mary's Stadium"),
("f057", "Sunderland", "0", "Stadium of Light"),
("f058", "Arsenal", "1", "Emirates"),
("f059", "West Bromwich Albion", "4", "The Hawthorns"),
("f060", "Stoke City", "1", "Britannia Stadium"),
("f061", "Hull City", "2", "KC Stadium"),
("f062", "Leicester City", "2", "King Power Stadium"),
("f063", "Liverpool", "2",  "Anfield"),
("f064", "Sunderland", "3", "Stadium of Light"),
("f065", "Swansea City", "2",  "Liberty Stadium"),
("f066", "Aston Villa", "0", "Villa Park"),
("f067", "Manchester United", "2", "Old Trafford"),
("f068", "Chelsea", "2", "Stamford Bridge"),
("f069", "Tottenham Hotspur", "1", "White Hart Lane"),
("f070", "West Ham", "2", "Upton Park"),
("f071", "Manchester City", "4", "City of Manchester Stadium"),
("f072", "Arsenal", "2", "Emirates"),
("f073", "Burnley", "1", "Turf Moor"),
("f074", "Crystal Palace", "1", "Selhurst Park"),
("f075", "Everton", "3", "Goodison Park"),
("f076", "Newcastle United", "1", "St James' Park"),
("f077", "Southampton", "8",  "St Mary's Stadium"),
("f078", "Queens Park Rangers", "2", "Loftus Road"),
("f079", "Stoke City", "2", "Britannia Stadium"),
("f080", "West Bromwich Albion", "2", "The Hawthorns"),
("f081", "West Ham", "2", "Upton Park"),
("f082", "Liverpool", "0", "Anfield"),
("f083", "Southampton", "1",  "St Mary's Stadium"),
("f084", "Sunderland", "0", "Stadium of Light"),
("f085", "West Bromwich Albion", "2", "The Hawthorns"),
("f086", "Swansea City", "2", "Liberty Stadium"),
("f087", "Burnley", "1", "Turf Moor"),
("f088", "Tottenham Hotspur", "1", "White Hart Lane"),
("f089", "Manchester United", "1", "Old Trafford"),
("f090", "Queens Park Rangers", "2", "Loftus Road"),
("f091", "Newcastle United", "1", "St James' Park"),
("f092", "Arsenal", "3",  "Emirates"),
("f093", "Chelsea", "2", "Stamford Bridge"),
("f094", "Everton", "0", "Goodison Park"),
("f095", "Hull City", "0", "KC Stadium"),
("f096", "Leicester City", "0", "King Power Stadium"),
("f097", "Stoke City", "2", "Britannia Stadium"),
("f098", "Manchester City", "1", "City of Manchester Stadium"),
("f099", "Aston Villa", "1", "Villa Park"),
("f100", "Crystal Palace", "1", "Selhurst Park");